name: Build and Push Image to Docker Hub

on:
  push:
    branches: ["master"]
  pull_request:
   branches: ["master"]


jobs:
   docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Image Build
        uses: docker/setup-buildx-action@v2
      -
        name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: rahatullah123  
          password: pakistan123PPPP
      -
        name: Image Push DockerHub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: rahatullah123/New:v3
