name: Complete_Life_cycle.yml

on:
  push:
    branches: ["master"]
  pull_request:
   branches: ["master"]


jobs:
   job1_public_runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Image Build
        uses: docker/setup-buildx-action@v2
        
      -
        name: Expression
        run: echo ${{github.sha}}
        
      -
        name: Branch Name
        run: echo running on branch ${GITHUB_REF##*/}
      -
        name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.USERNAME}}  
          password: ${{secrets.PASSWORD}} 
      
      -
        name: Image Push DockerHub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: rahatullah123/build_push_run:v3
          
   job2_public_runner:
    runs-on: [self-hosted, Linux ,X64,staging]
    steps:
  
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Image Build
        uses: docker/setup-buildx-action@v2
        
      -
        name: Expression
        run: echo ${{github.sha}}
        
      -
        name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.USERNAME}}  
          password: ${{secrets.PASSWORD}} 
      
     
      -
        name: Run Image
        run: sudo docker run -p 80:8080 -e APP_COLOR=green ahatullah123/build_push_run:v3
